# Generated by Django 5.1.3 on 2024-11-21 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gustohelado',
            name='categoria',
            field=models.CharField(choices=[('CREMAS', 'CREMAS'), ('CREMAS FRUTALES', 'CREMAS FRUTALES'), ('CHOCOLATE', 'CHOCOLATE'), ('DULCE DE LECHE', 'DULCE DE LECHE'), ('FRUTALES', 'FRUTALES')], default='crema', max_length=50),
        ),
    ]
